### PR TITLE
Fix like buttons being mismatched on newer layouts, also make replies better

### PR DESCRIPTION
**Pull request by Thespikedballofdoom**
Fixes like buttons being displaced without breaking existing compatibilities.
Also un-rounds most video thumbnails on watch page.
image

### CODE REVIEW

**Comment by KingGamingYT** [comment]
Comments:

The pull request's branch does not seem to work in chrome when sideloaded, I haven't tested firefox.
I recommend using some code from or a different workaround related to 1chan-level-journalist's CSS fix in #74 since it hides the ugly rounded button borders, and makes the Subscribe button red again (it doesn't adapt to if you have redux set to "Use Old Red" but that makes sense).

**Comment by Thespikedballofdoom** [comment]
thanks. Slightly sloppy copy pasting in chrome munted a ` and }. Identical to firefox now on my end,

**Review by KingGamingYT — COMMENTED** [review]
Everything looks mostly in check, however, I'll leave it up to people who know a bit more than I do for approval.

**Comment by Thespikedballofdoom** [comment]
I've fixed a lingering tiny css bug causing likes to fall down on the Dualcards experiment.

There are still some bugs caused by youtube's CSS. These are relatively easy fixes but I can't go in and do them all just for youtube to spin the slots again. I would strongly reccomend using stylus & css fixes for the moment so everyone can react fast. Perhaps a YT-redux-support style is in order. I could contribute to one but don't want to be the main writer of it.

**Comment by TorutheRedFox** [comment]
ayy mouth silence

**Comment by KingGamingYT** [comment]
Perhaps another addition to the PR would be to make the subscribe button actually line up with the count and bell again, as well as finding out how to revert it. (I've covered this somewhat also in #74 but since the post was closed I don't know if will receive anymore responses)

**Comment by Thespikedballofdoom** [comment]
> Perhaps another addition to the PR would be to make the subscribe button actually line up with the count and bell again, as well as finding out how to revert it. (I've covered this somewhat also in #74 but since the post was closed I don't know if will receive anymore responses)

There are still some bugs caused by youtube's CSS. These are relatively easy fixes but I can't go in and do them all just for youtube to spin the slots again. I would strongly reccomend using stylus & css fixes for the moment so everyone can react fast. Perhaps a YT-redux-support style is in order. I could contribute to one but don't want to be the main writer of it.

**Comment by KingGamingYT** [comment]
> > Perhaps another addition to the PR would be to make the subscribe button actually line up with the count and bell again, as well as finding out how to revert it. (I've covered this somewhat also in #74 but since the post was closed I don't know if will receive anymore responses)
> 
> There are still some bugs caused by youtube's CSS. These are relatively easy fixes but I can't go in and do them all just for youtube to spin the slots again. I would strongly reccomend using stylus & css fixes for the moment so everyone can react fast. Perhaps a YT-redux-support style is in order. I could contribute to one but don't want to be the main writer of it.

I saw this before you edited it out of your previous comment yesterday, and yeah, that makes sense for the time being.

**Comment by omnidevZero** [comment]
Thanks for the contribution! Actually I've begun to work on it some time ago but I _just_ got back to actually finishing it so the upcoming update will fix some of the issues. I'll push that first and afterwards I'll take a look at this PR again to see what can be cherry picked for additional fixes.

**Pull request closed without merging**
